apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-weekly-report
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/component: weekly-report
spec:
  schedule: "0 9 * * 1"
  jobTemplate:
    spec:
      backoffLimit: 6
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}-weekly-report
            app.kubernetes.io/name: {{ .Chart.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
            app.kubernetes.io/managed-by: {{ .Release.Service }}
            helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
            app.kubernetes.io/component: weekly-report
        spec:
          restartPolicy: OnFailure
          containers:
            - name: weekly-report
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command:
                - python
                - scripts/weekly_report.py
              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}-config
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
