apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-email-poller
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/component: email-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-email-poller
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-email-poller
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/component: email-poller
    spec:
      containers:
        - name: email-poller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - python
            - scripts/email_poller.py
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
